robot:
  wheelbase: 2.5
  kappa_max: 0.2
  steering_rate_max: 0.5
heuristic: dubins    # placeholder; currently stub uses euclidean
step:
  grid_resolution: 0.1
  c_min: 1.0
frontier:
  type: window
  delta: 1.0
  K: 512
  weight: 1.2
seeds: [1, 2, 3]
